apiVersion: v1
kind: ServiceAccount
metadata:
  name: goserver-sa

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role #or ClusterRole
metadata:
  name: server-read
rules:
- apiGroups: [""]
  resources: ["pods","services"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "watch", "list"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding #or ClusterRoleBinding
metadata:
  name: server-read-bind
subjects:
- kind: ServiceAccount
  name: goserver
  namespace: default
roleRef:
  kind: Role #or ClusterRole
  name: server-read
  apiGroup: rbac.authorization.k8s.io